<?php

/**
 * Implements hook_theme().
 */
function commerce_cart_blocks_theme($existing, $type, $theme, $path) {
  return [
    'commerce_cart_blocks_cart' => [
      'variables' => [
        'count' => NULL,
        'heading' => NULL,
        'content' => NULL,
        'in_cart' => NULL,
        'links' => [],
      ],
    ],
    'commerce_cart_blocks_cart_button' => [
      'variables' => [
        'count' => NULL,
        'icon' => NULL,
        'count_text' => '',
        'in_cart' => NULL,
        'url' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
